version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333

  spam-detection-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key-here
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_RAG_SERVER_URL=http://rag-server:6334
      - SPAM_DB_PATH=data/spam_numbers.db
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - qdrant
      - rag-server

  rag-server:
    build: .
    command: python rag/qdrant_rag_server.py
    ports:
      - "6334:6334"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant

volumes:
  qdrant_storage: